const mensagens = [
    "Você é minha pessoa favorita.",
    "Eu te amo com cada batida do meu coração.",
    "Você mudou minha vida completamente (pra melhor).",
    "Você é o meu maior orgulho.",
    "Vou estar aqui em todos os momentos, nunca esqueça disso.",
    "Você é o significado de felicidade.",
    "Você é a melhor coisa que aconteceu comigo.",
    "Você é o meu significado favorito do que é o amor.",
    "Eu te amo como eu nunca amei ninguém, você é o meu primeiro e único amor.",
    "Obrigada por existir e fazer da minha vida algo tão bonito.",
    "Você é tudo pra mim, obrigada por ter me dado uma perspectiva mais bonita do mundo.",
    "Eu te admiro muito, muito mesmo. Você é minha inspiração diária, eu quero ser como você quando eu crescer.",
    "Se eu pudesse, colocaria o mundo em uma peneira e tiraria todas as coisas ruins para te entregar só as coisas boas que esse mundo pode proporcionar.",
    "Se você soubesse o quanto eu te esperei... por isso, nunca tenha dúvidas sobre o meu amor por você.",
    "Você é meu raio de sol, e ilumina cada canto escuro da minha vida.",
    "Quando você chegou na minha vida, virou ela de cabeça pra baixo. Mal sabia eu que era exatamente o que precisava pra colocar tudo no seu devido lugar. Você organizou toda a bagunça que existia dentro de mim.",
    "Você coloriu minha vida com todos esses tons que compõem a sua pessoa — com o branco da sua pele, o castanho dos seus olhos e cabelos, sua boca rosada e todos os tons de azul que compõem sua alma. Você encheu de cores a minha paleta de tons neutros.",
    "Sua risada é minha risada favorita. Ela me faz rir com você.",
    "Cada partezinha de mim ama cada partezinha de você.",
    "Minha parte favorita do dia é estar com você.",
    "Você tem som de calmaria.",
    "Você me deu sonhos e a vontade de ter um futuro ao seu lado.",
    "Eu quero partilhar toda a minha existência ao seu lado.",
    "Prometo cuidar de você em todos os seus momentos até o fim da minha vida.",
    "Quero ser seu porto seguro, meu amor, e te proteger de todo mal que há no mundo.",
    "A primeira vez que meus olhos se encontraram com os seus, meu coração estremeceu, porque ele jamais tinha sentido um amor tão grande por alguém.",
    "Somos feitos de músicas antigas, filmes, azul e amarelo... e muito, muito amor.",
    "Você é meu presente de Deus.",
    "Eu te escolho todos os dias, e eu faria o mesmo em todas as outras vidas.",
    "Nossa conexão vem de vidas passadas. Nossas almas estão conectadas desde sua existência.",
    "Você é meu lugar favorito.",
    "Se eu soubesse que te encontraria no final, eu faria tudo de novo só pra te encontrar.",
    "Você faz com que as coisas tenham sentido.",
    "Você me ensinou o que é o amor. Aprendi o que é amar e, mais ainda, descobri o que é ser amada. Obrigada por isso.",
    "Você me cativa.",
    "Você me mostrou que o 'felizes para sempre' não existe apenas em contos de fadas.",
    "Não importa quantos 'eu te amo' eu diga, nunca vão parecer suficientes para demonstrar o amor que eu sinto por você.",
    "Você me completa.",
    "Eu nunca tive certeza de muita coisa, mas eu sempre tive certeza de você.",
    "Sou eternamente grata a Deus por ter te enviado a mim. Você faz com que eu seja uma pessoa melhor.",
    "Você é o príncipe que a mini Flávinha sempre sonhou.",
    "Você traz minha criança interior de volta, e ela ama você.",
    "Você é o motivo do meu sorriso mais sincero.",
    "Amo suas gracinhas. Nunca pare.",
    "Você é o meu sonho mais real.",
    "Você é o combustível da minha felicidade.",
    "Continue a nadar, continue a nadar, continue a nadar, nadar, nadar... - Procurando Nemo",
    "A flor que desabrocha na adversidade é a mais rara e bela de todas. - Mulan",
    "Uma vez eu ouvi que: 'O amor é colocar as necessidades de alguém acima das suas.' - Frozen. Aí cheguei à conclusão de que eu te amo.",
    "Quando estou com você, não me sinto tão sozinho. - Up: Altas Aventuras",
    "Você é meu maior presente. - Toy Story",
    "Eu prefiro morrer amanhã do que viver um século sem te conhecer. - Pocahontas",
    "Você é a razão pela qual eu acordo com um sorriso. - A Bela e a Fera",
    "'As melhores coisas da vida não podem ser vistas, apenas sentidas com o coração.' - O Pequeno Príncipe. E eu te sinto.",
    "Hakuna Matata. - O Rei Leão",
    "Sabe, minha risada favorita é a sua. - Up: Altas Aventuras",
    "Você é minha aventura favorita. - Up: Altas Aventuras",
    "Eu sou o que sou por causa de você. - O Rei Leão 2",
    "Você é do jeitinho que deveria ser. - Kung Fu Panda 3",
    "Acredite em você, porque eu acredito. - A Vida Secreta dos Bichos",
    "É incrível como uma pessoa pode mudar tudo na sua vida. - Simplesmente Acontece",
    "Eu te escreveria 365 cartas, uma por dia, se fosse preciso. - Diário de uma Paixão",
    "Você é meu agora. - A Culpa é das Estrelas",
    "Você é meu lugar favorito no mundo. - Para Todos os Garotos que Já Amei"
];

document.getElementById("clickButton").addEventListener("click", () => {
    const msg = mensagens[Math.floor(Math.random() * mensagens.length)];
    document.getElementById("mensagem").innerText = msg;
});
